// <auto-generated />
using System;
using FirmaPro.Dane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirmaPro.Dane.Migracje
{
    [DbContext(typeof(FirmaProDbContext))]
    [Migration("20260816180649_XmlFakturyZakupu")]
    partial class XmlFakturyZakupu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirmaPro.Dane.Encje.CzlonkostwoWFirmie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UzytkownikId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("UzytkownikId", "FirmaId")
                        .IsUnique();

                    b.ToTable("czlonkostwa", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.FakturaSprzedazy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DataPrzyjeciaKsef")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataSprzedazy")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataUjeciaVat")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DataUpoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataWystawienia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZaplaty")
                        .HasColumnType("date");

                    b.Property<Guid?>("FakturaKorygowanaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormaPlatnosci")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("KontrahentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("KorygowanaDataWystawienia")
                        .HasColumnType("date");

                    b.Property<string>("KorygowanaNumer")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KorygowanaNumerKsef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KursTabela")
                        .HasColumnType("text");

                    b.Property<decimal?>("KursWaluty")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("KursZDnia")
                        .HasColumnType("date");

                    b.Property<string>("MiejsceWystawienia")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NabywcaAdresLinia1")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NabywcaAdresLinia2")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("NabywcaGrupaVat")
                        .HasColumnType("boolean");

                    b.Property<bool>("NabywcaJst")
                        .HasColumnType("boolean");

                    b.Property<string>("NabywcaKodKraju")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("NabywcaKodUe")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("NabywcaNazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NabywcaNip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NabywcaNrVatUe")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NazwaBanku")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Numer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NumerKsef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NumerSesjiKsef")
                        .HasColumnType("text");

                    b.Property<string>("PodstawaZwolnienia")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrzyczynaKorekty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RachunekBankowy")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<decimal>("RazemBrutto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RazemNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RazemVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SkrotXml")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Stopka")
                        .HasMaxLength(3500)
                        .HasColumnType("character varying(3500)");

                    b.Property<DateOnly?>("TerminPlatnosci")
                        .HasColumnType("date");

                    b.Property<string>("TypKorekty")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("UpoXml")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UwagiKsef")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Waluta")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<byte[]>("XmlWyslany")
                        .HasColumnType("bytea");

                    b.Property<bool>("Zaplacono")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaKorygowanaId");

                    b.HasIndex("KontrahentId");

                    b.HasIndex("NumerKsef");

                    b.HasIndex("FirmaId", "DataUjeciaVat");

                    b.HasIndex("FirmaId", "DataWystawienia");

                    b.HasIndex("FirmaId", "Numer")
                        .IsUnique();

                    b.ToTable("faktury_sprzedazy", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.FakturaZakupu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataObowiazkuPodatkowego")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataUjecia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWplywu")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWystawienia")
                        .HasColumnType("date");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KontrahentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Numer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NumerKsef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Odliczany")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RazemBrutto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RazemNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RazemVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SprzedawcaNazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SprzedawcaNip")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uwagi")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Waluta")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<byte[]>("XmlKsef")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KontrahentId");

                    b.HasIndex("FirmaId", "DataUjecia");

                    b.HasIndex("FirmaId", "NumerKsef")
                        .IsUnique()
                        .HasFilter("\"NumerKsef\" IS NOT NULL");

                    b.HasIndex("FirmaId", "SprzedawcaNip", "Numer")
                        .IsUnique()
                        .HasFilter("\"SprzedawcaNip\" IS NOT NULL");

                    b.ToTable("faktury_zakupu", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Firma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdresLinia1")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AdresLinia2")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Aktywna")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("CertyfikatKsefZaszyfrowany")
                        .HasColumnType("bytea");

                    b.Property<string>("CertyfikatOdcisk")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CertyfikatPodmiot")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CertyfikatWaznyDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomyslnyTerminPlatnosciDni")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KodKraju")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("KodUrzeduSkarbowego")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("MetodaUwierzytelnienia")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MiejsceWystawienia")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NazwaBanku")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RachunekBankowy")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Srodowisko")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StopkaFaktury")
                        .HasMaxLength(3500)
                        .HasColumnType("character varying(3500)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("TokenKsefZaszyfrowany")
                        .HasColumnType("bytea");

                    b.Property<string>("TypOkresuVat")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nip");

                    b.ToTable("firmy", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Kontrahent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdresLinia1")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AdresLinia2")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("boolean");

                    b.Property<bool>("CzlonekGrupyVat")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("JednostkaPodrzednaJst")
                        .HasColumnType("boolean");

                    b.Property<string>("KodKraju")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("KodUe")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NrVatUe")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "Nazwa");

                    b.HasIndex("FirmaId", "Nip");

                    b.ToTable("kontrahenci", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.KwotaVatZakupu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FakturaZakupuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("KodStawki")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("Netto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaZakupuId", "KodStawki")
                        .IsUnique();

                    b.ToTable("kwoty_vat_zakupu", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Platnosc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Kwota")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Uwagi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.HasIndex("FirmaId", "FakturaId");

                    b.ToTable("platnosci", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaCennika", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktywna")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CenaNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Cn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gtu")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Indeks")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Jednostka")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("KodStawki")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Pkwiu")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "Aktywna", "Nazwa");

                    b.ToTable("cennik", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaFakturySprzedazy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CenaNetto")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Cn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gtu")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("Ilosc")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Indeks")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Jednostka")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KodStawki")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("KwotaVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("NrWiersza")
                        .HasColumnType("integer");

                    b.Property<string>("Pkwiu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("StanPrzed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WartoscNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId", "NrWiersza")
                        .IsUnique();

                    b.ToTable("pozycje_faktur_sprzedazy", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaWzorca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CenaNetto")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gtu")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<decimal>("Ilosc")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Jednostka")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KodStawki")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("NrWiersza")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WzorzecId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("WzorzecId");

                    b.ToTable("pozycje_wzorcow", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaZamowieniaFaktury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CenaNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gtu")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Ilosc")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Jednostka")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KodStawki")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("NrWiersza")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.HasIndex("FirmaId", "FakturaId");

                    b.ToTable("pozycje_zamowien", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.ResetHasla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UzytkownikId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("WaznoscDoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WykorzystanoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("UzytkownikId");

                    b.ToTable("resety_hasla", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.RozliczonaZaliczka", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Brutto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("DataWystawienia")
                        .HasColumnType("date");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Numer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NumerKsef")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZaliczkowaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.HasIndex("FirmaId", "ZaliczkowaId")
                        .IsUnique();

                    b.ToTable("rozliczone_zaliczki", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.SeriaNumeracji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Domyslna")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Miesiac")
                        .HasColumnType("integer");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OstatniNumer")
                        .HasColumnType("integer");

                    b.Property<int>("Rok")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Wzor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "Nazwa", "Rok", "Miesiac")
                        .IsUnique();

                    b.ToTable("serie_numeracji", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Uzytkownik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HaszHasla")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ImieINazwisko")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("StempelBezpieczenstwa")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("uzytkownicy", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.WyslanieFaktury", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("FakturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rodzaj")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UzytkownikId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("WyslanoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ZXmlem")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FakturaId");

                    b.HasIndex("FirmaId", "FakturaId");

                    b.ToTable("wysylki_faktur", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.WzorzecCykliczny", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktywny")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("Do")
                        .HasColumnType("date");

                    b.Property<int>("DzienMiesiaca")
                        .HasColumnType("integer");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FormaPlatnosci")
                        .HasColumnType("integer");

                    b.Property<Guid>("KontrahentId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("NastepneWystawienie")
                        .HasColumnType("date");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("Od")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OstatnieWystawienie")
                        .HasColumnType("date");

                    b.Property<string>("Rytm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("TerminPlatnosciDni")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KontrahentId");

                    b.HasIndex("FirmaId", "Aktywny", "NastepneWystawienie");

                    b.ToTable("wzorce_cykliczne", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.ZamkniecieOkresuVat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataZamkniecia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<long>("NadwyzkaDoPrzeniesienia")
                        .HasColumnType("bigint");

                    b.Property<int>("Numer")
                        .HasColumnType("integer");

                    b.Property<long>("PodatekDoWplaty")
                        .HasColumnType("bigint");

                    b.Property<int>("Rok")
                        .HasColumnType("integer");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId", "Typ", "Rok", "Numer")
                        .IsUnique();

                    b.ToTable("zamkniecia_okresow_vat", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Zaproszenie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("FirmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("PrzyjeteUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UtworzonoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WaznoscDoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ZapraszajacyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ZmienionoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("FirmaId", "Email");

                    b.ToTable("zaproszenia", (string)null);
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.CzlonkostwoWFirmie", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.Firma", "Firma")
                        .WithMany("Czlonkowie")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaPro.Dane.Encje.Uzytkownik", "Uzytkownik")
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.FakturaSprzedazy", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaSprzedazy", "FakturaKorygowana")
                        .WithMany()
                        .HasForeignKey("FakturaKorygowanaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmaPro.Dane.Encje.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaPro.Dane.Encje.Kontrahent", "Kontrahent")
                        .WithMany()
                        .HasForeignKey("KontrahentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FakturaKorygowana");

                    b.Navigation("Firma");

                    b.Navigation("Kontrahent");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.FakturaZakupu", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmaPro.Dane.Encje.Kontrahent", "Kontrahent")
                        .WithMany()
                        .HasForeignKey("KontrahentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Firma");

                    b.Navigation("Kontrahent");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.KwotaVatZakupu", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaZakupu", "Faktura")
                        .WithMany("Kwoty")
                        .HasForeignKey("FakturaZakupuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Platnosc", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaSprzedazy", "Faktura")
                        .WithMany()
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaFakturySprzedazy", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaSprzedazy", "Faktura")
                        .WithMany("Pozycje")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaWzorca", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.WzorzecCykliczny", "Wzorzec")
                        .WithMany("Pozycje")
                        .HasForeignKey("WzorzecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wzorzec");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.PozycjaZamowieniaFaktury", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaSprzedazy", "Faktura")
                        .WithMany("PozycjeZamowienia")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.ResetHasla", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.RozliczonaZaliczka", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaSprzedazy", "Faktura")
                        .WithMany("RozliczoneZaliczki")
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.WyslanieFaktury", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.FakturaSprzedazy", "Faktura")
                        .WithMany()
                        .HasForeignKey("FakturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faktura");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.WzorzecCykliczny", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.Kontrahent", "Kontrahent")
                        .WithMany()
                        .HasForeignKey("KontrahentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kontrahent");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.ZamkniecieOkresuVat", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Zaproszenie", b =>
                {
                    b.HasOne("FirmaPro.Dane.Encje.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.FakturaSprzedazy", b =>
                {
                    b.Navigation("Pozycje");

                    b.Navigation("PozycjeZamowienia");

                    b.Navigation("RozliczoneZaliczki");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.FakturaZakupu", b =>
                {
                    b.Navigation("Kwoty");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Firma", b =>
                {
                    b.Navigation("Czlonkowie");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.Uzytkownik", b =>
                {
                    b.Navigation("Czlonkostwa");
                });

            modelBuilder.Entity("FirmaPro.Dane.Encje.WzorzecCykliczny", b =>
                {
                    b.Navigation("Pozycje");
                });
#pragma warning restore 612, 618
        }
    }
}
